# tool path
competition_manager_path: /path/to/competition-manager/
loganalyzer_path: /path/to/loganalyzer3/
tournament_path: /path/to/tournament/

# username of servers and hosts
username: robocup

# API setting
slack_api_token: [slack_token]
dropbox_access_token: [dropbox_token]
dropbox_boot_dir: /testlog
google_drive_client_id: [client_id]
google_drive_client_secret: [client_secret]
google_drive_folder_id: [folder_id]
discord_token: [discord_token]
discord_channel_id: [channel_id]

# slack options
organizer_channel_name: [organizer_ch]
announce_channel_name:
 main_tournament_channel:
  slack: [slack_channel_name]
  discord: [discord_channel_id]
# sub_tournament_channel:
#  slack: []
#  discord: []


# competition options (do not contain spaces in competition_name)
competition_name: [CompetitionName]
# !!!!!
# teams are saved on HOME directory.
# The following setting are used to save archives at the competition-manager server. !!!!!
teams_dir: /path/to/archive/teams/
log_dir: /path/to/archive/logs/
